import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const response = await fetch(
    `${process.env.NEXT_PUBLIC_STRAPI_URL}/api/global-config?populate=*`
  );
  const data = await response.json();

  return (
    <html lang="pl">
      <body
        style={{ "--primary": data.data.primaryColor } as React.CSSProperties}
        className={`${jakarta.className} antialiased`}
      >
        <Header logo={data.data.logo} />
        <main>{children}</main>
        <Footer companyName={data.data.companyName} />
      </body>
    </html>
  );
}
